name: Maven Test with JDK 23

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'oracle'
          cache: 'maven'
          
      - name: Build and Run Tests
        run: |
          # Очистка старих збірок
          mvn clean
          
          # Завантаження залежностей без тестів
          mvn install -DskipTests=true
          
          # Запуск тестів (JUnit 5 теж підхопиться)
          mvn test

